//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_MaintenanceLogbook
    {
        public int Id { get; set; }
        public int AllocationMasterId { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string CompletionRemarks { get; set; }
        public int IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<bool> AdminApproval { get; set; }
        public Nullable<System.DateTime> AdminApprovalDate { get; set; }
        public string ApprovedBY { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> SAdminApproval { get; set; }
        public Nullable<System.DateTime> SAdminApprovaDate { get; set; }
        public string SAdminBy { get; set; }
    }
}
