//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_BreakdownLog
    {
        public int id { get; set; }
        public int MachineID { get; set; }
        public Nullable<int> SubUnitID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ProblemDescription { get; set; }
        public string ResolutionDetails { get; set; }
        public string Status { get; set; }
        public string ReportedBy { get; set; }
        public string ResolvedBy { get; set; }
        public int CompanyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsMaintDone { get; set; }
        public Nullable<System.DateTime> MaintDoneDate { get; set; }
        public string MaintDoneBy { get; set; }
        public string MaintRemarks { get; set; }
        public Nullable<bool> IsAdminDone { get; set; }
        public Nullable<System.DateTime> AdminDoneDate { get; set; }
        public string AdminDoneBy { get; set; }
    }
}
