//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_SubunitMaster
    {
        public int id { get; set; }
        public string SubUnitName { get; set; }
        public string Desc { get; set; }
        public Nullable<int> isdeleted { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> MachineID { get; set; }
    }
}
