//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_MachineMaster
    {
        public int id { get; set; }
        public string AssetID { get; set; }
        public string MachineName { get; set; }
        public string MachineDesc { get; set; }
        public Nullable<int> Department { get; set; }
        public byte[] UserManual { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> Isdeleted { get; set; }
        public Nullable<System.DateTime> CommisoningDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    }
}
