//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_FrequencyMaster
    {
        public int id { get; set; }
        public string FrequencyName { get; set; }
        public Nullable<int> Days { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> isdeleted { get; set; }
    }
}
