//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_AllocationMaster
    {
        public int id { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> SubUnitID { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> FrequencyID { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> LastMaintenanceDoneOn { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> TaskType { get; set; }
    }
}
