//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorizeddealerview
    {
        public int OrderId { get; set; }
        public string BranchOffice { get; set; }
        public string supplier_dealer { get; set; }
        public Nullable<int> Billingincentive { get; set; }
        public string PhaseDesc { get; set; }
        public string EngineModel { get; set; }
        public string RatingDesc { get; set; }
        public string OptionalLose { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> CformRcpt { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EndCusOrderPricewithGST { get; set; }
        public string BasicPrice { get; set; }
        public string CustomerName { get; set; }
    }
}
