//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoReminderEmail
    {
        public int id { get; set; }
        public string AutoReminderEmailFor { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> DurationHours { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
        public string EmailSubject { get; set; }
        public string EmailTitle { get; set; }
    }
}
