//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Series
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string Series { get; set; }
        public Nullable<int> Number { get; set; }
        public string Fin_Year { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
