//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int BOMid { get; set; }
        public Nullable<int> MasterItem { get; set; }
        public Nullable<int> ParentItem { get; set; }
        public Nullable<int> RawItem { get; set; }
        public Nullable<System.DateTime> BOMCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UOM { get; set; }
        public Nullable<int> Parentsub { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
