//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM_TestingUpdate
    {
        public int id { get; set; }
        public Nullable<int> BOMHeadid { get; set; }
        public Nullable<int> CPType { get; set; }
        public Nullable<int> CPRating { get; set; }
        public string CPSerialNumber { get; set; }
        public string CPRemarks { get; set; }
        public string BTMake { get; set; }
        public Nullable<int> BTRating { get; set; }
        public Nullable<decimal> BTQty { get; set; }
        public string BTSerial { get; set; }
        public Nullable<System.DateTime> TestingDate { get; set; }
        public Nullable<int> GensetRating { get; set; }
        public Nullable<decimal> CanopyQty { get; set; }
        public string LubeOil { get; set; }
        public string KCool { get; set; }
        public string KRMNo { get; set; }
        public string ADBlue { get; set; }
        public string SpecialRemarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    }
}
