//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bom_ProductionUpdate
    {
        public int id { get; set; }
        public Nullable<int> BOMHeadid { get; set; }
        public string EngineMake { get; set; }
        public Nullable<int> EngineModel { get; set; }
        public string EngineSerialNumber { get; set; }
        public string EngineTestCert { get; set; }
        public string EngineRemarks { get; set; }
        public string AlternatorMake { get; set; }
        public string AlternatorFrame { get; set; }
        public string AlternatorSerialNo { get; set; }
        public string AlternatorTestCert { get; set; }
        public string Alternatorwarranty { get; set; }
        public string AlternatorRemarks { get; set; }
        public Nullable<decimal> ExhaustPipe { get; set; }
        public string KGSticker { get; set; }
        public string AVMPads { get; set; }
        public Nullable<decimal> FuelSpout { get; set; }
        public Nullable<decimal> FlexibleBellow { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> AlternatorPhase { get; set; }
        public Nullable<int> AlternatorRating { get; set; }
    }
}
