//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMEwapDetail
    {
        public int id { get; set; }
        public Nullable<int> BomVoucherHeadID { get; set; }
        public Nullable<System.DateTime> Dateoftesting { get; set; }
        public string EngineSerialNumber { get; set; }
        public Nullable<int> Model { get; set; }
        public string AlternatorSerialNumber { get; set; }
        public string GensetRating { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> DispatchStatus { get; set; }
        public Nullable<System.DateTime> Dispatchon { get; set; }
        public string PanelSerialNo { get; set; }
        public string KRMNo { get; set; }
        public Nullable<int> BatteryRating { get; set; }
        public string BatterySerialNo { get; set; }
        public Nullable<int> BatteryQuantity { get; set; }
        public Nullable<int> ReturnStatus { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string FinYear { get; set; }
        public Nullable<int> PDIStatus { get; set; }
        public string PDIBy { get; set; }
        public Nullable<System.DateTime> PDIOn { get; set; }
    }
}
