//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMFinalProductCombination
    {
        public int id { get; set; }
        public Nullable<int> MasterProduct { get; set; }
        public Nullable<int> Canopy { get; set; }
        public Nullable<int> FuelTank { get; set; }
        public Nullable<int> Exhaust { get; set; }
        public Nullable<int> AcousticTreatment { get; set; }
        public Nullable<int> FinalPacking { get; set; }
        public Nullable<int> Assembly { get; set; }
        public Nullable<int> BaseFrame { get; set; }
        public Nullable<int> DGType { get; set; }
        public Nullable<int> Panel { get; set; }
        public Nullable<int> Alternator { get; set; }
        public Nullable<int> Electrical { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> ItemMasterID { get; set; }
    }
}
