//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMIndentHead
    {
        public int id { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<decimal> TotalItems { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Isclosed { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string FinYear { get; set; }
        public Nullable<int> SAdminApproval { get; set; }
        public string SAdminApprovalBy { get; set; }
        public Nullable<System.DateTime> SAdminApprovalDate { get; set; }
        public Nullable<int> Onhold { get; set; }
        public Nullable<System.DateTime> Holddatetime { get; set; }
        public string Holdby { get; set; }
        public string HoldRemarks { get; set; }
    }
}
