//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomIndentLine
    {
        public int id { get; set; }
        public Nullable<int> Headid { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<decimal> TotalQuantityRequired { get; set; }
        public Nullable<decimal> ShortQuantity { get; set; }
        public Nullable<decimal> ActualRequired { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<int> IsIndentRaised { get; set; }
        public Nullable<int> IsManualIndent { get; set; }
        public string LastOrderDate { get; set; }
        public Nullable<decimal> LastOrderQuantity { get; set; }
        public Nullable<int> PreviousSupplierid { get; set; }
        public Nullable<decimal> LastBasicRate { get; set; }
        public Nullable<decimal> AvailableStock { get; set; }
        public Nullable<decimal> AverageMonthlyConsumption { get; set; }
        public Nullable<System.DateTime> ExpectedStkEndDate { get; set; }
        public Nullable<int> Rejected { get; set; }
        public string Remarks { get; set; }
        public string UserRemarks { get; set; }
        public Nullable<decimal> QuantityRecieved { get; set; }
    }
}
