//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMItemMaster
    {
        public int Itemid { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Desc { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
        public Nullable<decimal> Minstklvl { get; set; }
        public Nullable<decimal> Maxstklvl { get; set; }
        public Nullable<decimal> MinimumOrderQuantity { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public Nullable<System.DateTime> ItemCreatedon { get; set; }
        public string Createdby { get; set; }
        public Nullable<decimal> RejectedStock { get; set; }
        public byte[] DrawingData { get; set; }
        public Nullable<int> ItemClass { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ItemGroup { get; set; }
        public Nullable<int> ItemLocation { get; set; }
        public Nullable<bool> FifoLot { get; set; }
    }
}
