//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMItemMasterLog
    {
        public int LogID { get; set; }
        public string ItemCode { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string OldItemName { get; set; }
        public string NewItemName { get; set; }
        public string OldDesc { get; set; }
        public string NewDesc { get; set; }
        public Nullable<decimal> OldMinStock { get; set; }
        public Nullable<decimal> NewMinStock { get; set; }
        public Nullable<decimal> OldMaxStock { get; set; }
        public Nullable<decimal> NewMaxStock { get; set; }
        public Nullable<decimal> OldStock { get; set; }
        public Nullable<decimal> NewStock { get; set; }
        public Nullable<decimal> OldMOQ { get; set; }
        public Nullable<decimal> NewMOQ { get; set; }
    }
}
