//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMRequisitionHead
    {
        public int id { get; set; }
        public Nullable<int> BOMVoucherID { get; set; }
        public Nullable<int> OldFGProductID { get; set; }
        public Nullable<int> NewFGProductID { get; set; }
        public string BOMReqeusitionNo { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string Fin_Year { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string ApprovedBy { get; set; }
    }
}
