//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMVoucherline
    {
        public int id { get; set; }
        public Nullable<int> BOMVoucherid { get; set; }
        public Nullable<int> Categoryid { get; set; }
        public Nullable<int> Subcategoryid { get; set; }
        public Nullable<int> Finalitemid { get; set; }
        public Nullable<int> rawitemid { get; set; }
        public Nullable<decimal> QuantityRequired { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public string UOM { get; set; }
        public Nullable<int> Stockapproved { get; set; }
        public string Approvedby { get; set; }
        public Nullable<System.DateTime> Approveddate { get; set; }
        public Nullable<int> Isdeleted { get; set; }
        public Nullable<int> LotID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> IsIssued { get; set; }
    }
}
