//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMVoucher
    {
        public int BOMVoucherID { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> Approvalstatus { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBY { get; set; }
        public Nullable<int> Ewap { get; set; }
        public Nullable<System.DateTime> EwapDate { get; set; }
        public string EwapBy { get; set; }
        public Nullable<int> FGProductID { get; set; }
        public Nullable<int> ProductionCompletionStatus { get; set; }
        public Nullable<System.DateTime> ProductionCompletionon { get; set; }
        public Nullable<int> DispatchStatus { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> Isdeleted { get; set; }
        public string CancelledRemarks { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Finyear { get; set; }
        public Nullable<int> PDIStatus { get; set; }
        public Nullable<System.DateTime> PDIon { get; set; }
        public string PDIBy { get; set; }
        public Nullable<bool> AllowNegativeTransaction { get; set; }
        public Nullable<bool> AllowLotCheck { get; set; }
        public Nullable<int> CurrentDeptID { get; set; }
        public Nullable<bool> IsFullyIssued { get; set; }
    }
}
