//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKL_Email_Setting
    {
        public int id { get; set; }
        public string smtp { get; set; }
        public string port { get; set; }
        public string ssl { get; set; }
        public string IT_password { get; set; }
    }
}
