//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKL_Feedback
    {
        public int id { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string UniqueKey { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public Nullable<int> PackingofPanel { get; set; }
        public Nullable<int> InteractionCall { get; set; }
        public Nullable<int> AfterSale { get; set; }
        public Nullable<int> Qualityofpanel { get; set; }
        public Nullable<int> Documentation { get; set; }
        public Nullable<int> PlantRating { get; set; }
        public Nullable<int> OverallRating { get; set; }
        public string OtherFeedback { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
