//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKL_Monthwise_View
    {
        public Nullable<int> SaleYear { get; set; }
        public string SaleMonth { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<long> TotalTaxValue { get; set; }
        public Nullable<long> GrossTotalAmount { get; set; }
        public int ID { get; set; }
    }
}
