//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKL_Enquiry
    {
        public int ID { get; set; }
        public string Billseries { get; set; }
        public int EnquiryNo { get; set; }
        public string Enquiry_Month { get; set; }
        public string Project_Client { get; set; }
        public string Contact_Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string TechnicalContact { get; set; }
        public string FinancialContact { get; set; }
        public string Email { get; set; }
        public string ReceivedFrom { get; set; }
        public Nullable<System.DateTime> ReceivedDT { get; set; }
        public Nullable<System.DateTime> SentDT { get; set; }
        public string Statuss { get; set; }
        public string Remarks { get; set; }
        public string EnquiryType { get; set; }
        public string Year { get; set; }
        public string EnterDT { get; set; }
        public string EnterTM { get; set; }
        public string EnterBy { get; set; }
        public Nullable<int> TotalBasicValue { get; set; }
        public Nullable<int> TotalTaxValue { get; set; }
        public Nullable<int> GrossTotalAmount { get; set; }
        public string Industry { get; set; }
        public string OANumber { get; set; }
        public string OADT { get; set; }
        public string PONumber { get; set; }
        public string PODT { get; set; }
        public string GST { get; set; }
        public string GST1 { get; set; }
        public string PAN { get; set; }
        public string PAN1 { get; set; }
        public string BillingAddress { get; set; }
        public string ShippingAddress { get; set; }
        public string Jobnumber { get; set; }
        public string GADrawing { get; set; }
        public string SingleDrawing { get; set; }
        public string WiringDrawing { get; set; }
        public string BillDrawing { get; set; }
        public string Freight { get; set; }
        public string Insurance { get; set; }
        public string DeliveryDT { get; set; }
        public string DeliveryRemarks { get; set; }
        public string ApprovedBy { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> OAStage { get; set; }
        public string DrawingApp { get; set; }
        public string POCopy { get; set; }
        public string OARemarks { get; set; }
        public string DAppDT { get; set; }
        public string DAppTM { get; set; }
        public Nullable<System.DateTime> DAP { get; set; }
        public Nullable<System.DateTime> PCD { get; set; }
        public string ProductionDoc { get; set; }
        public Nullable<System.DateTime> ProdComplete { get; set; }
        public string QualityDoc { get; set; }
        public Nullable<System.DateTime> QualityComplete { get; set; }
        public string Billcopy { get; set; }
        public string LRCopy { get; set; }
        public string EwayCopy { get; set; }
        public string TruckCopy { get; set; }
        public string PackingList { get; set; }
        public Nullable<System.DateTime> DispatchComplete { get; set; }
        public string DriverName { get; set; }
        public string TruckNumber { get; set; }
        public string DriverContact { get; set; }
        public string MechanicalPart { get; set; }
        public string AsbuiltDRW { get; set; }
        public string CustomerRPT { get; set; }
        public Nullable<System.DateTime> EnquiryStatusDT { get; set; }
        public Nullable<System.DateTime> DrawingUploadDT { get; set; }
        public Nullable<System.DateTime> OAApproveDT { get; set; }
        public Nullable<System.DateTime> OAEnterDT { get; set; }
        public string EnquiryN { get; set; }
        public Nullable<decimal> FreightAMT { get; set; }
        public string CAD { get; set; }
        public Nullable<System.DateTime> CADUploadDate { get; set; }
    }
}
