//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKL_Enquiry_Item
    {
        public int ID { get; set; }
        public string Billseries { get; set; }
        public int EnquiryNo { get; set; }
        public string Item_Desc { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Unitprice { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public string Rone { get; set; }
        public string RTwo { get; set; }
        public string Rthree { get; set; }
        public string Rfour { get; set; }
        public string Rfive { get; set; }
        public string Year { get; set; }
        public string EnterDT { get; set; }
        public string EnterTM { get; set; }
        public string EnterBy { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string EnquiryN { get; set; }
    }
}
