//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchDetail
    {
        public int id { get; set; }
        public Nullable<int> Ewapid { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> FGItemCode { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string CreatedBy { get; set; }
        public string CustomerLocation { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> DispatchReturn { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string FinYear { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TotalAMT { get; set; }
        public Nullable<decimal> FrieghtAMT { get; set; }
        public Nullable<decimal> BillingAMT { get; set; }
        public string Transport { get; set; }
        public string LR { get; set; }
        public string LorryNo { get; set; }
        public string EwayNo { get; set; }
        public string Erection { get; set; }
        public string ErectionDetail { get; set; }
        public Nullable<System.DateTime> LRDate { get; set; }
        public string CustomerGST { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public string Biltyno { get; set; }
    }
}
