//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchReturnBOMLine
    {
        public int id { get; set; }
        public Nullable<int> MasterItemID { get; set; }
        public Nullable<int> RawitemID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubcategoryID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> HeadID { get; set; }
    }
}
