//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchReturnBOMHead
    {
        public int id { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> FGItemID { get; set; }
        public Nullable<int> DispatchReturnID { get; set; }
        public Nullable<int> HeadApproalStatus { get; set; }
        public Nullable<System.DateTime> HeadApprovalDate { get; set; }
        public Nullable<int> BOMID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string HeadApprovedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string FinYear { get; set; }
    }
}
