//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchReturn
    {
        public int id { get; set; }
        public Nullable<int> Dispatchid { get; set; }
        public Nullable<int> Ewapid { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> QualityStatus { get; set; }
        public string QualityRemarks { get; set; }
        public Nullable<System.DateTime> QualityDate { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> HeadStatus { get; set; }
        public Nullable<System.DateTime> HeadDate { get; set; }
        public Nullable<int> FGProductID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string FinYear { get; set; }
    }
}
