//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineRating
    {
        public int EngRatId { get; set; }
        public Nullable<int> EngineId { get; set; }
        public string EngineModel { get; set; }
        public Nullable<int> RateId { get; set; }
        public string RatingDesc { get; set; }
    }
}
