//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPLStockIN_Detail
    {
        public int Id { get; set; }
        public int HeadId { get; set; }
        public int ItemCode { get; set; }
        public decimal Quantity { get; set; }
        public int QualityApproved { get; set; }
        public Nullable<decimal> QualityApprovedQty { get; set; }
        public Nullable<System.DateTime> QApprovedDate { get; set; }
        public Nullable<decimal> RejectedQuantity { get; set; }
        public string RejectionRemarks { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> BillQuantity { get; set; }
        public Nullable<int> Taxid { get; set; }
        public Nullable<int> RejectionReturn { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string LotNo { get; set; }
    }
}
