//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPLStockIssueDetail
    {
        public int id { get; set; }
        public Nullable<int> Voucherid { get; set; }
        public Nullable<int> Itemcodeid { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public Nullable<int> ApprovedStatus { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Voucher { get; set; }
        public Nullable<decimal> RejectedQuantity { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
