//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPLStockReturnHead
    {
        public int id { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> BomVoucherid { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Fin_Year { get; set; }
        public Nullable<int> RefChallanId { get; set; }
        public Nullable<bool> IsChallanReturn { get; set; }
    }
}
