//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPLStockIssueHead
    {
        public int id { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Fin_Year { get; set; }
        public Nullable<bool> IsChallan { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<bool> IsReturnable { get; set; }
        public string Remarks { get; set; }
        public string BillingAddress { get; set; }
        public string TransportName { get; set; }
        public Nullable<bool> IsBilty { get; set; }
        public string BiltyNo { get; set; }
        public Nullable<System.DateTime> BiltyDate { get; set; }
        public Nullable<decimal> BiltyTotalValue { get; set; }
        public string BiltyDescription { get; set; }
    }
}
