//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPL_MiscSale_Head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IEPL_MiscSale_Head()
        {
            this.IEPL_MiscSale_Detail = new HashSet<IEPL_MiscSale_Detail>();
        }
    
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string GSTNo { get; set; }
        public decimal TotalBasic { get; set; }
        public decimal TotalTax { get; set; }
        public decimal NetAmount { get; set; }
        public int CompanyID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TaxType { get; set; }
        public Nullable<decimal> TCS_Percent { get; set; }
        public Nullable<decimal> TCS_Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IEPL_MiscSale_Detail> IEPL_MiscSale_Detail { get; set; }
    }
}
