//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPLStockIN_Head
    {
        public int Id { get; set; }
        public string BillNumber { get; set; }
        public System.DateTime BillDate { get; set; }
        public string PoNumber { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Vouchernumber { get; set; }
        public string GRNumber { get; set; }
        public Nullable<System.DateTime> GRDate { get; set; }
        public string GateEntry { get; set; }
        public Nullable<System.DateTime> GateEntryDate { get; set; }
        public Nullable<int> Supplierid { get; set; }
        public Nullable<int> BillClosed { get; set; }
        public string BillCloseby { get; set; }
        public Nullable<System.DateTime> BillClosedatetime { get; set; }
        public Nullable<int> Taxid { get; set; }
        public Nullable<decimal> OtherTaxPercent { get; set; }
        public Nullable<decimal> frieghtamount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> OtherTaxAmount { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> BillAmountOnBill { get; set; }
        public Nullable<decimal> TaxAmountOnBill { get; set; }
        public Nullable<int> MRNStatus { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Fin_Year { get; set; }
        public Nullable<int> MRNStoreApproval { get; set; }
        public Nullable<int> MRNQualityApproval { get; set; }
        public Nullable<int> MRNPlantHeadApproval { get; set; }
        public Nullable<int> MRNAccountApproval { get; set; }
        public Nullable<int> PurchaseType { get; set; }
        public Nullable<int> Isdeleted { get; set; }
        public string DeletionRemarks { get; set; }
        public Nullable<decimal> FrieghtTaxAmount { get; set; }
    }
}
