//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPLQualityRejectionDetail
    {
        public int id { get; set; }
        public Nullable<int> Headid { get; set; }
        public Nullable<int> PurchaseDetailid { get; set; }
        public Nullable<decimal> RejectionQuantity { get; set; }
        public Nullable<int> RejectiontoPlant { get; set; }
        public Nullable<int> RejectiontoVendor { get; set; }
        public Nullable<int> RejectionLocation { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<int> RejectionType { get; set; }
        public string FinYear { get; set; }
    }
}
