//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEPL_MiscSale_Detail
    {
        public int DetailId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public int TaxID { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal LineTotal { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual IEPL_MiscSale_Head IEPL_MiscSale_Head { get; set; }
    }
}
