//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterGFE
    {
        public int id { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string Productcode { get; set; }
        public string Itemname { get; set; }
        public string itemdesc { get; set; }
        public string Itemcategory { get; set; }
        public string norms { get; set; }
        public string unitofmeasurement { get; set; }
        public string Phase { get; set; }
        public Nullable<int> presentstock { get; set; }
        public Nullable<int> transit { get; set; }
        public Nullable<int> phylogistic { get; set; }
        public Nullable<int> phyplant { get; set; }
        public Nullable<int> readyforallocation { get; set; }
        public Nullable<int> wip { get; set; }
        public Nullable<int> testing { get; set; }
        public Nullable<int> Rejectedstk { get; set; }
    }
}
