//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IECEntities : DbContext
    {
        public IECEntities()
            : base("name=IECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMKL_Enquiry> CMKL_Enquiry { get; set; }
        public virtual DbSet<CMKL_Stage> CMKL_Stage { get; set; }
        public virtual DbSet<CMKL_Email> CMKL_Email { get; set; }
        public virtual DbSet<Tender> Tenders { get; set; }
        public virtual DbSet<tbl_User_Master> tbl_User_Master { get; set; }
        public virtual DbSet<TA_TypeMaster> TA_TypeMaster { get; set; }
        public virtual DbSet<TA_Transport> TA_Transport { get; set; }
        public virtual DbSet<TA_Master> TA_Master { get; set; }
        public virtual DbSet<CMKL_Enquiry_Item> CMKL_Enquiry_Item { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<PurchaseGFE> PurchaseGFEs { get; set; }
        public virtual DbSet<TA_head> TA_head { get; set; }
        public virtual DbSet<TA_items> TA_items { get; set; }
        public virtual DbSet<Purchasestage> Purchasestages { get; set; }
        public virtual DbSet<ItemMasterGFE> ItemMasterGFEs { get; set; }
        public virtual DbSet<PurchaseQualityRejectionreason> PurchaseQualityRejectionreasons { get; set; }
        public virtual DbSet<PurchaseStatusQuality> PurchaseStatusQualities { get; set; }
        public virtual DbSet<PurchaseitemGFE> PurchaseitemGFEs { get; set; }
        public virtual DbSet<EmpCompany> EmpCompanies { get; set; }
        public virtual DbSet<EngineModel> EngineModels { get; set; }
        public virtual DbSet<EngineRating> EngineRatings { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<CMKL_FinYear> CMKL_FinYear { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Authorizeddealerview> Authorizeddealerviews { get; set; }
        public virtual DbSet<PaymentsDealer> PaymentsDealers { get; set; }
        public virtual DbSet<PaymentCompany> PaymentCompanies { get; set; }
        public virtual DbSet<PaymentViewCompany> PaymentViewCompanies { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<BOMCategory> BOMCategories { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<BOM_UOM> BOM_UOM { get; set; }
        public virtual DbSet<BOMSubcategory> BOMSubcategories { get; set; }
        public virtual DbSet<BOMVPartwiseApprove> BOMVPartwiseApproves { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<SupplierMaster> SupplierMasters { get; set; }
        public virtual DbSet<TaxMaster> TaxMasters { get; set; }
        public virtual DbSet<IEPLStockInQualityTransaction> IEPLStockInQualityTransactions { get; set; }
        public virtual DbSet<IEPLStockIN_Detail> IEPLStockIN_Detail { get; set; }
        public virtual DbSet<BOMItemMasterLog> BOMItemMasterLogs { get; set; }
        public virtual DbSet<RejectionArea> RejectionAreas { get; set; }
        public virtual DbSet<RejectionType> RejectionTypes { get; set; }
        public virtual DbSet<IEPLQualityRejectionDetail> IEPLQualityRejectionDetails { get; set; }
        public virtual DbSet<IEPLQualityRejectionHead> IEPLQualityRejectionHeads { get; set; }
        public virtual DbSet<OpeningStock> OpeningStocks { get; set; }
        public virtual DbSet<MRNDetail> MRNDetails { get; set; }
        public virtual DbSet<Make_Master> Make_Master { get; set; }
        public virtual DbSet<PurchaseOrderHead> PurchaseOrderHeads { get; set; }
        public virtual DbSet<PurchaseOrderUpdationlog> PurchaseOrderUpdationlogs { get; set; }
        public virtual DbSet<CMKL_Email_Setting> CMKL_Email_Setting { get; set; }
        public virtual DbSet<Bill_Series> Bill_Series { get; set; }
        public virtual DbSet<StockTable> StockTables { get; set; }
        public virtual DbSet<CompanyActiveForStock> CompanyActiveForStocks { get; set; }
        public virtual DbSet<FinYear> FinYears { get; set; }
        public virtual DbSet<CMKL_QRLogin> CMKL_QRLogin { get; set; }
        public virtual DbSet<MRNDetailLog> MRNDetailLogs { get; set; }
        public virtual DbSet<BOM_NegativeStock> BOM_NegativeStock { get; set; }
        public virtual DbSet<BOMFinalProductCombination> BOMFinalProductCombinations { get; set; }
        public virtual DbSet<BOMRequisitionHead> BOMRequisitionHeads { get; set; }
        public virtual DbSet<BOMVoucherline> BOMVoucherlines { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<BatteryMaster> BatteryMasters { get; set; }
        public virtual DbSet<BOMRequisitionLine> BOMRequisitionLines { get; set; }
        public virtual DbSet<ConnectionData> ConnectionDatas { get; set; }
        public virtual DbSet<ItemMasterClass> ItemMasterClasses { get; set; }
        public virtual DbSet<BOMItemMaster> BOMItemMasters { get; set; }
        public virtual DbSet<PurchaseType> PurchaseTypes { get; set; }
        public virtual DbSet<IEPLStockIN_Head> IEPLStockIN_Head { get; set; }
        public virtual DbSet<BomIndentLine> BomIndentLines { get; set; }
        public virtual DbSet<BOMVoucher> BOMVouchers { get; set; }
        public virtual DbSet<BOMEwapDetail> BOMEwapDetails { get; set; }
        public virtual DbSet<DispatchReturn> DispatchReturns { get; set; }
        public virtual DbSet<AutoReminderEmail> AutoReminderEmails { get; set; }
        public virtual DbSet<DispatchReturnBOMLine> DispatchReturnBOMLines { get; set; }
        public virtual DbSet<DispatchReturnBOMHead> DispatchReturnBOMHeads { get; set; }
        public virtual DbSet<ItemGroup> ItemGroups { get; set; }
        public virtual DbSet<LineRejectionHead> LineRejectionHeads { get; set; }
        public virtual DbSet<LineRejectionDetail> LineRejectionDetails { get; set; }
        public virtual DbSet<Bom_ProductionUpdate> Bom_ProductionUpdate { get; set; }
        public virtual DbSet<ControlPanelType> ControlPanelTypes { get; set; }
        public virtual DbSet<Ratings_Production> Ratings_Production { get; set; }
        public virtual DbSet<BOM_TestingUpdate> BOM_TestingUpdate { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<StoreLocationMaster> StoreLocationMasters { get; set; }
        public virtual DbSet<BOMIndentHead> BOMIndentHeads { get; set; }
        public virtual DbSet<Asset_MachineMaster> Asset_MachineMaster { get; set; }
        public virtual DbSet<Asset_SubunitMaster> Asset_SubunitMaster { get; set; }
        public virtual DbSet<Asset_FrequencyMaster> Asset_FrequencyMaster { get; set; }
        public virtual DbSet<Asset_TastMaster> Asset_TastMaster { get; set; }
        public virtual DbSet<Asset_TaskItems> Asset_TaskItems { get; set; }
        public virtual DbSet<Asset_MaintenanceLogbookItems> Asset_MaintenanceLogbookItems { get; set; }
        public virtual DbSet<Asset_MaintenanceLogbook> Asset_MaintenanceLogbook { get; set; }
        public virtual DbSet<Asset_AllocationMaster> Asset_AllocationMaster { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<CMKL_Feedback> CMKL_Feedback { get; set; }
        public virtual DbSet<Asset_UserTaskAllocation> Asset_UserTaskAllocation { get; set; }
        public virtual DbSet<Asset_TaskType> Asset_TaskType { get; set; }
        public virtual DbSet<EnableLotDetail> EnableLotDetails { get; set; }
        public virtual DbSet<Stock_lotDetail> Stock_lotDetail { get; set; }
        public virtual DbSet<Asset_BreakdownLog> Asset_BreakdownLog { get; set; }
        public virtual DbSet<DispatchDetail> DispatchDetails { get; set; }
        public virtual DbSet<IEPLStockIssueDetail> IEPLStockIssueDetails { get; set; }
        public virtual DbSet<IEPLStockIssueHead> IEPLStockIssueHeads { get; set; }
        public virtual DbSet<IEPLStockReturnDetail> IEPLStockReturnDetails { get; set; }
        public virtual DbSet<IEPLStockReturnHead> IEPLStockReturnHeads { get; set; }
        public virtual DbSet<User_Access> User_Access { get; set; }
        public virtual DbSet<User_Menu> User_Menu { get; set; }
        public virtual DbSet<IEPL_MiscSale_Detail> IEPL_MiscSale_Detail { get; set; }
        public virtual DbSet<IEPL_MiscSale_Head> IEPL_MiscSale_Head { get; set; }
    }
}
