//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRNDetail
    {
        public int id { get; set; }
        public string MRNNumber { get; set; }
        public Nullable<int> HeadID { get; set; }
        public Nullable<System.DateTime> MRNDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
