//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRNDetailLog
    {
        public int id { get; set; }
        public Nullable<int> HeadID { get; set; }
        public string StoreApprovalBY { get; set; }
        public string QualityApprovalBY { get; set; }
        public string PlantHeadApprovalBY { get; set; }
        public string AccountApprovalBY { get; set; }
        public Nullable<System.DateTime> StoreADate { get; set; }
        public Nullable<System.DateTime> QualityADate { get; set; }
        public Nullable<System.DateTime> PlantHeadADate { get; set; }
        public Nullable<System.DateTime> AccountADate { get; set; }
    }
}
