//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseitemGFE
    {
        public int id { get; set; }
        public int Billid { get; set; }
        public Nullable<int> itemid { get; set; }
        public string norms { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> basicprice { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> approved { get; set; }
        public string Logisticindate { get; set; }
        public string Plantindate { get; set; }
        public string productserialno { get; set; }
        public string QualityRemarks { get; set; }
        public Nullable<int> Quaitystatus { get; set; }
        public Nullable<int> Qualityreason { get; set; }
        public string Qualitydate { get; set; }
        public string QualityDocument { get; set; }
    }
}
