//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public int id { get; set; }
        public Nullable<int> HeadID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> ItemTaxID { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> NetBasic { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
