//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHead
    {
        public int id { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string IndentNumber { get; set; }
        public Nullable<int> IndentID { get; set; }
        public Nullable<System.DateTime> IndentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string FrieghtType { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<int> FrieghtTaxID { get; set; }
        public Nullable<decimal> FrieghtTax { get; set; }
        public Nullable<decimal> TotalFrieght { get; set; }
        public string InsuranceType { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<int> InsuranceTaxID { get; set; }
        public Nullable<decimal> InsuranceTax { get; set; }
        public Nullable<decimal> Totalinsurance { get; set; }
        public string PFType { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<int> PFTaxID { get; set; }
        public Nullable<decimal> PFTax { get; set; }
        public Nullable<decimal> TotalPF { get; set; }
        public string OtherType { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<int> OtherTaxID { get; set; }
        public Nullable<decimal> OtherTax { get; set; }
        public Nullable<decimal> TotalOther { get; set; }
        public string DeliveryMode { get; set; }
        public string Remarks { get; set; }
        public string PaymentTerms { get; set; }
        public string TaxTypeOnBill { get; set; }
        public Nullable<decimal> BillTaxableAmount { get; set; }
        public Nullable<decimal> BillTotalTax { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> BillGrossAmount { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<int> AdminApproval { get; set; }
        public Nullable<int> SAdminApproval { get; set; }
        public Nullable<int> Isdeleted { get; set; }
        public string Fin_Year { get; set; }
        public Nullable<bool> IsservicePO { get; set; }
    }
}
