//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderUpdationlog
    {
        public int id { get; set; }
        public Nullable<int> POid { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
    }
}
