//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseGFE
    {
        public int id { get; set; }
        public Nullable<int> company { get; set; }
        public string Billno { get; set; }
        public string billdate { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> purchaseapproval { get; set; }
        public Nullable<int> Billqty { get; set; }
        public string createdon { get; set; }
    }
}
