//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTable
    {
        public int id { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> Minstklvl { get; set; }
        public Nullable<decimal> Maxstklvl { get; set; }
        public Nullable<decimal> MOQ { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
        public Nullable<int> LastSupplierid { get; set; }
        public Nullable<decimal> LastDiscount { get; set; }
        public Nullable<decimal> RejectedStock { get; set; }
    }
}
