//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_lotDetail
    {
        public int id { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<System.DateTime> RecieptDateTime { get; set; }
        public string Lot_SerialNumber { get; set; }
        public Nullable<decimal> OriginalQuantity { get; set; }
        public Nullable<decimal> CurrentQuantity { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> ReceivingLineID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public string ReservedTo { get; set; }
    }
}
