//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierMaster
    {
        public int id { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContactName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string SupplierAddress { get; set; }
        public string GSTNumber { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string State { get; set; }
        public string SupplierAddress1 { get; set; }
    }
}
