//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_head
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string journeyfrom { get; set; }
        public string journeyto { get; set; }
        public string Dateofleavinghq { get; set; }
        public string Dateofarrivalhq { get; set; }
        public Nullable<int> Advance { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> balance { get; set; }
        public Nullable<int> Approvalstatus { get; set; }
    }
}
