//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_items
    {
        public int id { get; set; }
        public Nullable<int> taid { get; set; }
        public string tatype { get; set; }
        public string locationfrom { get; set; }
        public string locationto { get; set; }
        public string mode { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
