//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_Master
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string JourneyFrom { get; set; }
        public string journeyto { get; set; }
        public Nullable<System.DateTime> DateofLeaving { get; set; }
        public Nullable<System.DateTime> DateofArrival { get; set; }
        public Nullable<decimal> TransportExpense { get; set; }
        public Nullable<decimal> HotelExpenseTTL { get; set; }
        public Nullable<decimal> LocalExpenseTTL { get; set; }
        public string DADays { get; set; }
        public Nullable<decimal> DAAmountTTL { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<decimal> AdvanceTaken { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
    }
}
