//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_Transport
    {
        public int id { get; set; }
        public Nullable<int> TAid { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Mode { get; set; }
        public string TicketAttach { get; set; }
        public string TAType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
