//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Master
    {
        public int Id { get; set; }
        public string user_name { get; set; }
        public string User_Address { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string User_Mobile { get; set; }
        public string user_password { get; set; }
        public string User_Email1 { get; set; }
        public string User_EmailPwd { get; set; }
        public string user_Role { get; set; }
        public string User_status { get; set; }
        public string Verified { get; set; }
        public Nullable<System.DateTime> AccountCreateDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string smtpServerIP { get; set; }
        public string mailUserId { get; set; }
        public string mailUserPassword { get; set; }
        public Nullable<int> ClientIPAddId { get; set; }
        public string User_Email2 { get; set; }
        public string User_Email3 { get; set; }
        public string EndCustomer { get; set; }
        public string Updatenotification { get; set; }
        public string SignURL { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
