//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender
    {
        public int ID { get; set; }
        public string Buyer { get; set; }
        public string Rating { get; set; }
        public Nullable<int> FeesAmount { get; set; }
        public string Feetype { get; set; }
        public string TenderNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Quantity { get; set; }
        public string Participated { get; set; }
        public Nullable<System.DateTime> ParticipatedDate { get; set; }
        public string Portal { get; set; }
        public Nullable<System.DateTime> OfflinesubmissionDate { get; set; }
        public string EMDExemption { get; set; }
        public string Time { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
