//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMKL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Access
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MenuAccess { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
